### ISSUE TITLE
ci: Consider adding GitHub Pages deployment Action

### ISSUE THREAD

**Issue by minagishl** [ns-knowledgebase/shiritori#5]
現在、個人のリポジトリを Org リポジトリに移行しましたが、リポジトリの詳細ページに記載されているウェブサイトの URL が旧リポジトリでホスティングしている URL のままになっており、最新のアプリケーションを利用できない状態です
そこで、GitHub Actions を使用して GitHub Pages にホスティングする方法を検討しています
この点について、ご意見をいただけますでしょうか？

**Comment by tukiminya** [comment]
遅くなりました！
私は問題ないかと思いますが、学外が絡んでくるので @GakutoHirose も本件確認いただけますか？

**Comment by GakutoHirose** [comment]
ありがとうございます！特に個人情報の取扱もありませんし、こちらから取得する情報もないかと考えています。
その点、懸念はありませんので公開ください！一方、noindexには設定したく、その設定だけおねがいします！

**Comment by minagishl** [comment]
@GakutoHirose 承知しました
